(() => {
  const URL='https://qdehfgjifhtczkrpuadl.supabase.co';
  const KEY='sb_publishable_ChrvUYG2OES6q2kCpkBJcA_uaAmfOVp';
  let db=null, boardTimer=null, countdownTimer=null;
  const $=s=>document.querySelector(s);
  function css(){if($('#jnxGameHubStyles'))return;const s=document.createElement('style');s.id='jnxGameHubStyles';s.textContent=`
#jnxGameHub,#jnxNumberGame{position:fixed;inset:0;z-index:35000;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.68);backdrop-filter:blur(7px);box-sizing:border-box}#jnxGameHub.open,#jnxNumberGame.open{display:flex}.jgh-box{position:relative;width:min(760px,95vw);max-height:88dvh;overflow:auto;padding:26px;border:1px solid rgba(255,255,255,.12);border-radius:22px;background:#171526;color:#fff;box-sizing:border-box}.jgh-close{position:absolute;right:14px;top:12px;width:36px;height:36px;border-radius:50%;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.08);color:#fff;font-size:21px}.jgh-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:20px}.jgh-card{min-height:150px;padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.05);color:#fff;text-align:left;cursor:pointer}.jgh-card:hover{background:rgba(255,255,255,.08)}.jgh-cover{font-size:38px}.jgh-title{display:block;font-size:18px;font-weight:800;margin-top:12px}.jgh-desc{display:block;color:#999;font-size:12px;margin-top:5px;line-height:1.5}.rng-top{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.rng-pill{padding:9px 12px;border-radius:12px;background:rgba(255,255,255,.06);font-size:13px}.rng-number{font-size:clamp(44px,10vw,78px);font-weight:900;letter-spacing:3px;text-align:center;margin:22px 0 8px}.rng-score{text-align:center;color:#aaa;font-size:14px}.rng-roll{display:block;width:min(320px,100%);margin:18px auto;padding:13px;border:0;border-radius:14px;background:#8267d4;color:#fff;font-weight:800;font-size:16px}.rng-roll:disabled{opacity:.45}.rng-traits{display:flex;gap:7px;flex-wrap:wrap;justify-content:center;min-height:30px}.rng-trait{padding:6px 9px;border-radius:999px;background:rgba(130,103,212,.18);font-size:12px}.rng-cols{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:22px}.rng-panel{padding:14px;border-radius:16px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08)}.rng-panel h3{margin:0 0 10px;font-size:15px}.rng-row{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:12px}.rng-row:last-child{border-bottom:0}.rng-note{font-size:11px;color:#777;line-height:1.5;margin-top:12px}html.jnxLight .jgh-box{background:#fff;color:#242130;border-color:rgba(100,75,180,.2)}html.jnxLight .jgh-card,html.jnxLight .rng-panel,html.jnxLight .rng-pill{background:#f8f6ff;color:#242130;border-color:rgba(100,75,180,.15)}html.jnxLight .jgh-close{background:#eee9fa;color:#31274f}@media(max-width:600px){.jgh-box{width:100%;padding:22px 15px}.jgh-grid,.rng-cols{grid-template-columns:1fr}.jgh-card{min-height:120px}.rng-number{letter-spacing:1px}}
`;document.head.appendChild(s)}
  function ui(){if($('#jnxGameHub'))return;css();const hub=document.createElement('div');hub.id='jnxGameHub';hub.innerHTML=`<section class="jgh-box"><button class="jgh-close" data-close="hub">×</button><h2>🎮 小游戏</h2><div style="color:#8f899a;font-size:13px">JNX Games · 点击游戏封面进入</div><div class="jgh-grid"><button class="jgh-card" data-game="woodfish"><span class="jgh-cover">🪵</span><span class="jgh-title">功德木鱼</span><span class="jgh-desc">敲木鱼、今日排行与每日榜一奖励</span></button><button class="jgh-card" data-game="rng"><span class="jgh-cover">🎲</span><span class="jgh-title">概率数字</span><span class="jgh-desc">抽取 0–999999，按数字特征的稀有程度获得独立分数</span></button></div></section>`;const game=document.createElement('div');game.id='jnxNumberGame';game.innerHTML=`<section class="jgh-box"><button class="jgh-close" data-close="rng">×</button><h2>🎲 概率数字</h2><div class="rng-top"><div class="rng-pill">机会 <b id="rngEnergy">–/5</b></div><div class="rng-pill">恢复 <b id="rngNext">–</b></div><div class="rng-pill">共享数据每 1 分钟刷新</div></div><div id="rngNumber" class="rng-number">——</div><div id="rngScore" class="rng-score">抽取后显示稀有分数</div><div id="rngTraits" class="rng-traits"></div><button id="rngRoll" class="rng-roll">抽取数字</button><div class="rng-cols"><div class="rng-panel"><h3>🏆 站内最高记录</h3><div id="rngBoard">加载中…</div></div><div class="rng-panel"><h3>🕘 最近抽取</h3><div id="rngRecent">加载中…</div></div></div><div class="rng-note">分数只属于这个小游戏，不兑换 JNX 积分或奖品。分数由回文、重复数字、质数、完全平方数、连续数字等特征的出现概率加权，并限制在 6 位数以内。</div></section>`;document.body.append(hub,game);hub.querySelector('[data-close="hub"]').onclick=()=>hub.classList.remove('open');game.querySelector('[data-close="rng"]').onclick=()=>{game.classList.remove('open');openHub()};hub.onclick=e=>{if(e.target===hub)hub.classList.remove('open');const card=e.target.closest('[data-game]');if(!card)return;if(card.dataset.game==='rng')openRng();else openWoodfish()};$('#rngRoll').onclick=roll}
  async function ready(){if(db)return true;for(let i=0;i<40;i++){if(window.supabase?.createClient){db=window.supabase.createClient(URL,KEY);return true}await new Promise(r=>setTimeout(r,100))}return false}
  function openHub(){ui();$('#jnxNumberGame')?.classList.remove('open');$('#jnxGameHub').classList.add('open')}
  function openWoodfish(){ui();$('#jnxGameHub').classList.remove('open');const b=$('#jnxGameLauncher');if(b)b.click();setTimeout(()=>{const x=$('#wfClose');if(x&&!x.dataset.jnxBack){x.dataset.jnxBack='1';x.addEventListener('click',()=>setTimeout(openHub,0))}},50)}
  async function openRng(){ui();$('#jnxGameHub').classList.remove('open');$('#jnxNumberGame').classList.add('open');if(!await ready())return;await Promise.all([state(),board()]);clearInterval(boardTimer);boardTimer=setInterval(board,60000);clearInterval(countdownTimer);countdownTimer=setInterval(state,1000)}
  async function state(){if(!db||!$('#jnxNumberGame')?.classList.contains('open'))return;const {data,error}=await db.rpc('jnx_number_state');if(error)return;$('#rngEnergy').textContent=`${data.energy}/5`;$('#rngNext').textContent=data.energy>=5?'已满':`${data.next_in}s`;$('#rngRoll').disabled=data.energy<=0}
  async function board(){if(!db)return;const {data,error}=await db.rpc('jnx_number_board');if(error)return;$('#rngBoard').innerHTML=(data.leaderboard||[]).map((r,i)=>`<div class="rng-row"><span>${i+1}. ${esc(r.player)}</span><b>${Number(r.score).toLocaleString()}</b></div>`).join('')||'<div class="rng-note">还没有记录</div>';$('#rngRecent').innerHTML=(data.recent||[]).slice(0,8).map(r=>`<div class="rng-row"><span>${esc(r.player)} · ${String(r.rolled_number).padStart(6,'0')}</span><b>${Number(r.score).toLocaleString()}</b></div>`).join('')||'<div class="rng-note">还没有记录</div>'}
  async function roll(){if(!await ready())return;const b=$('#rngRoll');b.disabled=true;b.textContent='抽取中…';const {data,error}=await db.rpc('jnx_number_roll');b.textContent='抽取数字';if(error){await state();return}$('#rngNumber').textContent=String(data.number).padStart(6,'0');$('#rngScore').textContent=`稀有分数 ${Number(data.score).toLocaleString()}`;$('#rngTraits').innerHTML=(data.traits||[]).map(t=>`<span class="rng-trait">${esc(t)}</span>`).join('')||'<span class="rng-trait">普通数字</span>';await Promise.all([state(),board()])}
  function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
  window.__jnxOpenGameHub=openHub;window.__jnxOpenNumberGame=openRng;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui,{once:true});else ui();
})();